../../../rtl/com/urv_cfg.sv
../../../rtl/com/urv_typedef.sv
../../../rtl/com/component.v
../../../rtl/com/inst_index.v
../../../rtl/com/macro.v
../../../rtl/com/async_fifo.sv
../../../rtl/core/reg.v
../../../rtl/core/acu.v
../../../rtl/core/pc.v
../../../rtl/core/ifu.v
../../../rtl/core/div.sv
../../../rtl/core/muldiv.sv
../../../rtl/core/muldiv_vio.sv
../../../rtl/core/idu.v
../../../rtl/core/exu.v
../../../rtl/core/lsu.sv
../../../rtl/core/wbu.sv
../../../rtl/core/bpu.v
../../../rtl/core/core_top.sv

../../../../../project/develop/cpu/hardware/design/rtl/common/cells/std_dff.sv
../../../../../project/develop/cpu/hardware/design/rtl/common/cells/std_dffr.sv
../../../../../project/develop/cpu/hardware/design/rtl/common/rivai_ip/ot_flop_fifo.v
../../../rtl/mem/ram.sv

../../../rtl/mem/mem.sv
../../../rtl/noc/mem_noc_router_1to2.sv
../../../rtl/noc/mem_noc_router_1to4.sv
../../../rtl/noc/mem_noc_arb_2to1.sv
../../../rtl/noc/mem_noc.sv
../../../rtl/noc/cdc_mem_noc.sv
../../../rtl/peri/clint/clint.sv
../../../rtl/peri/plic/plic.sv
../../../rtl/peri/testio/testio_trx.sv
../../../rtl/peri/testio/testio_slv.sv
../../../rtl/peri/testio/testio_ma.sv
-F ../../../../../project/develop/cpu/hardware/design/rtl/flist/rct_pdk_lib.syn.f
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/async_fifo.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/async_fifo_th.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/async_reg_bus.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/async_wb.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/clk_buf.v
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/clk_ctl.v
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/clk_skew_adjust.gv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/ctech_cells.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/double_sync_high.v
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/double_sync_low.v
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/pulse_gen_type1.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/pulse_gen_type2.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/registers.v
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/reset_sync.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/ser_inf_32b.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/ser_shift.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/sync_fifo.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/sync_fifo2.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/sync_wbb.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/wb_interface.v
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/lib/wb_stagging.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/uart/src/uart_cfg.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/uart/src/uart_core.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/uart/src/uart_rxfsm.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/uart/src/uart_txfsm.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/uart_top/uart_top.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/uart2wb/src/uart2_core.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/uart2wb/src/uart2wb.sv
../../../../../project/develop/cpu/hardware/design/rtl/soc/riscduino/verilog/rtl/uart2wb/src/uart_msg_handler.v
# -F ../../../../../project/develop/cpu/hardware/design/rtl/flist/user_project_wrapper.syn.f
# ../../../rtl/soc/usoc.sv
# ../../../verif/tb/usoc_tb.v
../../../rtl/cpu/cpu_top.sv
../../../verif/tb/cpu_top_tb.sv
