../../../rtl/com/urv_cfg.sv
../../../rtl/com/urv_typedef.sv
../../../rtl/com/component.v
../../../rtl/com/inst_index.v
../../../rtl/com/macro.v
../../../rtl/com/async_fifo.sv
../../../rtl/com/fast_sram_sp.v
#../../../rtl/com/ot_flop_fifo.v
../../../rtl/cpu/core/reg.v
../../../rtl/cpu/core/acu.v
../../../rtl/cpu/core/pc.v
../../../rtl/cpu/core/ifu.v
../../../rtl/cpu/core/div.sv
#../../../rtl/cpu/core/muldiv.sv
../../../rtl/cpu/core/muldiv_vio.sv
../../../rtl/cpu/core/idu.v
../../../rtl/cpu/core/exu.v
../../../rtl/cpu/core/lsu.sv
../../../rtl/cpu/core/wbu.sv
../../../rtl/cpu/core/bpu.v
../../../rtl/cpu/core/icache_ctrl.sv

#../../../rtl/mem/boot_rom.sv
../../../rtl/mem/urv_sram.sv
../../../rtl/mem/urv_sram_burst.sv
../../../rtl/noc/mem_noc_router_1to2.sv
../../../rtl/noc/mem_noc_router_1to4.sv
../../../rtl/noc/imem_noc_router_1to2.sv
../../../rtl/noc/dmem_noc_router_1to4.sv
../../../rtl/noc/mem_noc_arb_2to1.sv
../../../rtl/noc/mem_noc_router.sv
../../../rtl/noc/mem_noc_sync.sv
../../../rtl/noc/mem_noc.sv
../../../rtl/noc/cdc_mem_noc.sv
../../../rtl/peri/clint/clint.sv
../../../rtl/peri/plic/plic.sv
#../../../rtl/peri/dp/dp_trx.sv
#../../../rtl/peri/dp/mem2dp.sv
#../../../rtl/peri/dp/sdp2mem.sv
# ../../../rtl/soc/usoc.sv
# ../../../verif/tb/usoc_tb.v
../../../rtl/cpu/core/urv_core.sv
../../../rtl/cpu/uncore/urv_uncore.sv
../../../rtl/cpu/urv_cpu.sv
../../../verif/tb/urv_cpu_tb.sv